### ISSUE TITLE
Rename action

### ISSUE THREAD

**Issue by PaulRBerg** [smol-ninja/bulloak-toolchain#1]
It's likely that Bulloak will continue to evolve and support multiple features, e.g. https://github.com/alexfertel/bulloak/issues/86

This makes the current name rather limiting. A more expansive one would be `bulloak-action` or `bulloak-toolchain` (mirroring [foundry-toolchain](https://github.com/foundry-rs/foundry-toolchain)).

**Comment by smol-ninja** [comment]
Good point. I will rename it to `bulloak-toolchain` since, as it grows, it can represent more than just one action.

PS: I wanted to begin with that but since the action only verifies the structure at the moment, I decided to go ahead with a bespoke name.

**Comment by PaulRBerg** [comment]
Sounds good!
